### ISSUE TITLE
Iron SPI file get stuck after many transactions

### ISSUE THREAD

**Issue by gvauvert** [Axway/iron#43]
## Description
Iron SPI file get stuck under highly concurrent access : 

### Reproduction Steps
- Apply patch [HighlyConcurrentFileStoreTest.zip](https://github.com/Axway/iron/files/1942984/HighlyConcurrentFileStoreTest.zip)
- Run the test (Not Debug, because it does not get stuck in Debug)

### Actual result
- After minutes, no more transactions are created (around 3 000 are created, but 10 000 expected) - see iron\iron\iron-spi-file-inttest\iron-store-XXX\tx
- Never terminates

### Expected result
- Terminates after 10 000 transactions

**Comment by frouge-axway** [comment]
[_HighlyConcurrentFileStoreTest_V2.zip](https://github.com/Axway/iron/files/3261953/_HighlyConcurrentFileStoreTest_V2.zip)

**Comment by frouge-axway** [comment]
[Snapshots.zip](https://github.com/Axway/iron/files/3262243/Snapshots.zip)
2 snapshot, one during debug and one during run 
we can use the compare funtion of yourkit to see the difference of time.

**Comment by gvauvert-axway** [comment]
After many transactions, iron get stuck because
`Cache<String, CompletableFuture<List<Object>>> io.axway.iron.core.internal.StoreManagerImpl#m_futuresBySynchronizationId`
removes values when it is full.
These values should not be removed because wrapped by CommandFutureWrapper to be retained as string reference:
`    /**
     * Directly send every calls to the wrapped {@code Future}. This class is needed to retain a strong reference to the underlying transaction {@code Future}.<br>
     * So it prevents the transaction {@code Future} to be evicted from the {@link #m_futuresBySynchronizationId} weak cache, giving the opportunity to the
     * transaction {@code Future} to be completed, and so the command {@code Future} can complete also.
     */
    private static final class CommandFutureWrapper<T> implements Future<T> {`

**Comment by gvauvert-axway** [comment]
Fixed in iron 0.18.0
