### ISSUE TITLE
Improvement of snapshot management

### ISSUE THREAD

**Issue by gvauvert-axway** [Axway/iron#82]
- manage the 1000 objects limitation returned by listObjects
- manage the situation of a snapshot is read during a snapshot written in progress

**Comment by gvauvert-axway** [comment]
A new layout has been introduced, with a new Migration tool from file SPI to AWS SPI.

**Comment by sdaclin** [comment]
+ upgrade of Jackson-databind to 2.9.9 (security issue)

**Comment by sdaclin** [comment]
Done
